### ISSUE TITLE
Merge strawberry-django-plus into this repo

### ISSUE THREAD

**Issue by bellini666** [strawberry-graphql/strawberry-graphql-django#139]
There are a lot of features on [strawberry-django-plus](https://github.com/blb-ventures/strawberry-django-plus) that not only are usually requested by the community, they really would benefit this project.

I would like to make this a meta issue for discussing which features should be ported.

Here is a list of features that I think should be ported, linked to their respective issues:

- [ ] Better typing for exposed api (#36)
- [ ] Improve attribute resolving by avoiding sync_to_async overhead when the value is already cached (#137)
- [ ] Query optimizer that automatically adds `select_related`/`prefetch_related`/`only` optimizations to querysets (#75)
- [ ] Support for model `property`(#134)
- [ ] Better mutations handling, with support for nested inputs (#133 and #67)

Those here needs further discussion to know if they are interesting for this project or not, since they are integrations with 3rd party libs:

- [ ] Built-in support for django-debug-toolbar (#138)
- [ ] Built-in support for using django's `TextChoices` as enums. This is implemented in `strawberry-django-plus` with the help of [django-choices-field](https://github.com/bellini666/django-choices-field) (#65 and #66)

Those would be better ported with support on `strawberry` first:

- [ ] Relay-style pagination support (https://github.com/strawberry-graphql/strawberry/issues/1573)
- [ ] Relay-style input support that automatically converts function args to an input (https://github.com/strawberry-graphql/strawberry/issues/1573)
- [ ] Permissioned resolvers that uses the django authentication system implemented as directives (https://github.com/strawberry-graphql/strawberry/issues/1694)

**Comment by oleksandr-luxmedien** [comment]
I would love to see that to happened!

**Comment by bellini666** [comment]
This is finally resolved by https://github.com/strawberry-graphql/strawberry-graphql-django/releases/tag/v0.10.0 :)
